### ISSUE TITLE
Feedback for "Privileges and Permissions"

### ISSUE THREAD

**Issue by MartinSautterAnalytics4you** [SAP-docs/sap-datasphere#11]
https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html?locale=en-US

Clearify:

-for Permisson of Analytical Model and connectiosn
Whats the difference in haveing CRUD and/or Manintain Authorizations

-for Permisson of Activity LogWhats the difference in haveing R and/or Manintain Authorizations

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

- for Permission of Analytical Model and connections (what are the differences between having CRUD and/or Maintain Authorizations?)
Sorry, I do not understand your question. Could you please rephrase your question? Can you also please write the names of the privileges exactly like the are written in the page so that I know what you’re referring to? Thanks for your help.

-for Permisson of Activity Log  (What is the difference in having R and/or Manintain Authorizations?)
As stated in the page, the “Activity Log” privilege does not include the permission “Maintain”. This privilege only includes the permissions “Read” and “Delete”.


Thank you and best regards
Cindy

**Comment by MartinSautterAnalytics4you** [comment]
Hello,

 

soma taks have Maintain ( and Manage) permissions.

These permissions seem to be redundant, conflicting or contradictionary
to the Create Read Update Delete Permssions if switched entirely or partitally on.

 

 

For example:

Fort he task „Analytical Models“ exist the permissions Maintain permisson and Maintain


What is the difference in the permssions if Create Read Update Delete is switched On partially or entriely and if the Maintain permisson is siwtched ?

What does the Permission Maintain do what the Create Read Update Delete Permission ( if set ) does no do ?

What is if Create Read Update Delete Permissions are set partially and the Maintain permisson is set ?

 

 

The same question for any Task which has Maninatin permssions 

A Clearification and/or Defintion of the Maintain and Manage Permission in the SAP Help would be helpfull .

What do they do ? Especiylly in coopertaion with Create Read Update Delete Permssions switched entirely or partitally on.

Vielen Dank !  Thank You !
Viele Grüße ! Best Wishes  !

Dipl.Ing. Martin Sautter
SAP Analytics Beratung

 
USt Nr DE326947352
Steuernr 18641172
ANALYTICS4YOU.NET
Über der Klause 12
D 81545 München
0049 089 6 42 37 28
0049 0176 87 58 09 66
 ***@***.***> ***@***.***

 

Von: CindyVenet ***@***.***> 
Gesendet: Freitag, 12. Mai 2023 11:12
An: SAP-docs/sap-datasphere ***@***.***>
Cc: MartinSautterAnalytics4you ***@***.***>; Author ***@***.***>
Betreff: Re: [SAP-docs/sap-datasphere] Feedback for "Privileges and Permissions" (Issue #11)

 

Dear SAP Datasphere User

*	for Permission of Analytical Model and connections (what are the differences between having CRUD and/or Maintain Authorizations?)
Sorry, I do not understand your question. Could you please rephrase your question? Can you also please write the names of the privileges exactly like the are written in the page so that I know what you’re referring to? Thanks for your help.

-for Permisson of Activity Log (What is the difference in having R and/or Manintain Authorizations?)
As stated in the page, the “Activity Log” privilege does not include the permission “Maintain”. This privilege only includes the permissions “Read” and “Delete”.

Thank you and best regards
Cindy

**Comment by CindyVenet** [comment]
Dear SAP Datasphere user

Thanks again for your feedback.

You can see the definition of each permission at the end of the topic Privileges and Permissions:
https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/d7350c6823a14733a7a5727bad8371aa.html#permissions

Please let me know if the definition for Maintain and Manage are not clear.

Some privileges are inherited from SAP Analytics Cloud. This is the case of “Analytic Model”. 

You can see information about this in this topic of the SAP Analytics Cloud help: https://help.sap.com/docs/SAP_ANALYTICS_CLOUD/00f68c2e08b941f081002fd3691d86a7/93fec5646f144e109745ce74fd492c3f.html

Please let me know if this helps.
Best regards
Cindy for the User Assistance team

**Comment by MartinSautterAnalytics4you** [comment]
Hi Cindy,
if You look more into the table some stuff gets clearfied but more holes in the SAP Help appear,
its not up to date.
I give You some hints what You have to improve:

-for privilege  type Users, privilege   Manage:
The table explains Manage

-for privilege  type teams, privilege  Manage,:
explanation missing in table

-Privilege Type: "Connection" , Public-,Private-, Deleted Files, Ownership of Content
-where what files ?
- does not exits in the SAP Help , pl. add

-for privilege  type lifecyell, privilege  Manage, and others
explanation missing in table ( for all Permission), please add, not underrstandable what this should do

-guessing remains  for Privilege Type: Spaces: 
SAP HELP:
"Manage: When granted on Spaces and Space Files, permits full control over all spaces and the data inside these spaces."
 Is MANAGE is redundant to CRUD or not  ?
not understandabke needs to be overworked good

-Privilege Type: Space File 
according to 
"When granted on Spaces and Space Files, permits full control over all spaces and the data inside these spaces."
CRUD is the same than Manage.
Clearify.


further:
Chapter "Example: Space Management App Permissions" clearly not understanable what concept what it shows.
News syntax added wo definition and so on.

Let me know when You have overworked it. 
I can read than over it.

Best Martin

**Comment by OliviaValeano** [comment]
Dear SAP Datasphere user,

Thanks again for your valuable feedback.

Some of the  issues you've identified are linked to issues in the user interface, which we’ve reported to the development team. 

For privileges Spaces and Space Files, the Manage permission is intended only for tenant administrators in order to give them access to all spaces. They need in addition the relevant CRUD permissions to create, update or delete spaces. We’ve amended the documentation accordingly. 

The section “Example: Space Management App Permissions" has been rewritten and will appear as a section in the topic [Privileges by App and Feature](https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/2d8b7d04dcae402f911d119437ce0a74.html).

Please note that these changes will be available in the Help Portal in version 2023.14.

Also, we’ll continue to update the documentation as we receive answers from our development team.

Best regards,
Olivia, from the User Assistance team
