### ISSUE TITLE
Feedback for "Data Lake API"

### ISSUE THREAD

**Issue by michael-eaton** [SAP-docs/sap-datasphere#13]
https://help.sap.com/docs/SAP_DATASPHERE/be5967d099974c69b77f4549425ca4c0/12b6825ac6d34db9902460f665cfcb88.html?locale=en-US

The 3 links in this page result in _Sorry We couldn't find that page._

**Comment by CindyVenet** [comment]
Dear SAP Datasphere User

Thank you for reporting these wrong links! We'll look into them and come back to you soon.

best regards

the UA team

**Comment by OliviaValeano** [comment]
Dear SAP Datasphere User, 

The broken links have been fixed and will be visible in version 2023.14.

The documentation will look like this:
![image](https://github.com/SAP-docs/sap-datasphere/assets/135343102/f7be2972-9d80-4c60-b00e-5d108299d551)
 
So that you can already use the links, here they are:
[What's the Difference Between Data Lake Relational Engine and SAP HANA Database SQL Statements?](https://help.sap.com/docs/SAP_HANA_DATA_LAKE/9220e7fec0fe4503b5c5a6e21d584e63/f23b60ec161a46f9b906eac15c5a3b95.html)
[System Views in Data Lake Relational Engine (SAP HANA DB-Managed)](https://help.sap.com/docs/SAP_HANA_DATA_LAKE/a898e08b84f21015969fa437e89860c8/92e2e6c466d844e0b0e961069aa3b8d7.html)
[Query Data in Data Lake Relational Engine (SAP HANA DB-Managed)](https://help.sap.com/docs/SAP_HANA_DATA_LAKE/9220e7fec0fe4503b5c5a6e21d584e63/9c80f123c5d74f71a9f536682f2f479c.html)

Thanks a lot for your contribution.

Best regards,
The UA Team
