### ISSUE TITLE
Information on Data Flows and Replication Flows need updates

### ISSUE THREAD

**Issue by Sebastian-Haase-SAP** [SAP-docs/sap-datasphere#19]
### Issue description

Data Flow
- OnPremise vs. Cloud is not clearly specified. First bullet points states a Cloud Connector needs to be installed -> this is only releveant if SAP source system is located OnPremise
- "For SAP S/4HANA, source version 1909 FPS01 plus SAP Note 2873666 or higher versions are supported." => this is outdated. Just state that availablity can be checked in SAP note "2890171-SAP Data Intelligence / SAP Datasphere - ABAP Integration" and corrections need to be applied.
- The SLT Information is incorrect - we never supported 1709 as SLT => check SAP Note 2890171. All the version information should be replaced with this reference.
- Name of the communication scenario 532 has changed - it is best to not mention the name

Replication Flow
- support of CDS is not mentioned
- it already links to the correct note to check for needed versions - it is better not to duplicate the content on this page as updates may be missed

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Prepare Connectivity to SAP ABAP Systems

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/76c9ac1a318c4de2bea29e72c64be8a0.html?locale=en-US&state=PRODUCTION&version=cloud

**Comment by co-sti** [comment]
Dear Sebastian,
thanks for your feedback. I'm working on it and will send a draft version for a review.
Best Regards,
Conny

**Comment by co-sti** [comment]
Hi @Sebastian-Haase-SAP ,

in the prerequisites sections for data flows and replication flows, I've now mainly kept the following:

- some Cloud Connector information and links 
- the disclaimer about minimum requirement for source versions incl. the link to SAP Note https://me.sap.com/notes/2890171
- a cross reference to the SAP S/4HANA Cloud prerequisites

See: https://help.sap.com/docs/SAP_DATASPHERE/9f804b8efa8043539289f42f372c4862/76c9ac1a318c4de2bea29e72c64be8a0.html?state=DRAFT&version=DEV

Regarding the detailed points:
**Data Flow**
1. OnPremise vs. Cloud is not clearly specified. First bullet points states a Cloud Connector needs to be installed -> this is only releveant if SAP source system is located OnPremise 
[Conny: The information was available in the text, but I tried to make it more clear now; some smaller formatting changes will follow]
2. "For SAP S/4HANA, source version 1909 FPS01 plus SAP Note 2873666 or higher versions are supported." => this is outdated. Just state that availablity can be checked in SAP note "2890171-SAP Data Intelligence / SAP Datasphere - ABAP Integration" and corrections need to be applied.  
[Conny:  has been removed and replaced by disclaimer + 2890171 note link]
3. The SLT Information is incorrect - we never supported 1709 as SLT => check SAP Note 2890171. All the version information should be replaced with this reference.
[Conny:  has been changed accordingly by fully removing the information and replacing it by disclaimer + 2890171 note link]
4. Name of the communication scenario 532 has changed - it is best to not mention the name 
[Conny: has been changed ]

Note that I haven't used the different data sources as a criterion to structure the prerequisites as with the given information this doesn't seem to be necessary. 

**Replication Flow**

1. support of CDS is not mentioned
[Conny: data source support in detail is mentioned in the connection type docs; in the prerequisites topic here, I have only put a cross-reference to the SAP S/4HANA Cloud prerequisites because of the communication arrangement(s) required in this case]
2. it already links to the correct note to check for needed versions - it is better not to duplicate the content on this page as updates may be missed
[Conny:  has been changed accordingly by fully removing the information and replacing it by disclaimer + 2890171 note link]

Please let me know if there is some important information missing or if there is something wrong or misleading.

Thanks and best Regards,
Conny

**Comment by Sebastian-Haase-SAP** [comment]
Looks good - thank you for all the updates!
